config/routes.rb
HumanFaktor::Application.routes.draw do

  ###
  # routes for base
  #
  
  # NNB: be sure to update the subdomain validator options for account to 
  #      include these paths as restricted names

  get "contact", :to => 'home#contact', :as => :home_contact
  get "features", :to => 'home#features', :as => :home_features
  get "subscriptions", :to => 'home#subscriptions', :as => :home_subscriptions
  get "terms", :to => 'home#terms', :as => :home_terms
  get "privacy", :to => 'home#privacy', :as => :home_privacy
  get "partner", :to => 'home#partner', :as => :home_partner
  get "sign_in", :to => 'home#sign_in', :as => :home_sign_in

  get "demo_request", :to => 'demo_requests#new', :as => :new_demo_request
  post "demo_request", :to => 'demo_requests#create', :as => :create_demo_request

  get "registrations/new", :to => 'registrations#new', :as => :new_account_registration
  post "registrations", :to => 'registrations#create', :as => :create_account_registration
  get "registrations/:id", :to => 'registrations#show', :as => :account_registration
  get "registrations/:id/query/:started(.:format)", :to => 'registrations#query', :as => :query_account_registration

  ###
  # routes for tenant administration
  #

  scope 'admin' do

    devise_for :tenant_admins, :path => "" do
      # TODO: additional configuration for devise
    end

    get "impersonate/:id", :to => 'tenant_admin#impersonate', :as => :impersonate
    get ":id", :to => 'tenant_admin#show', :as => :show_account
    get "/", :to => 'tenant_admin#index', :as => :tenant_admin

  end

  ###
  # routes for tenant
  #

  # NOTE: this part of the route is "globbed" and there are some issues 
  #       in Rails when there are nested routes, so a `:tenant => current_account.subdomain` option 
  #       is required for url helpers when constructing paths
  scope "*tenant" do

    get "setup", :to => "tenant/account_setup#edit", :as => :account_setup
    put "setup", :to => "tenant/account_setup#update", :as => :update_account_setup

    devise_for :employees, :path => "" do
      # TODO: additional configuration for devise
    end

    get "welcome", :to => "tenant/dashboard#welcome", :as => :welcome

    # dashboard
    get "balance", :to => "tenant/dashboard#balance", :as => :balance

    get "staff_balance", :to => "tenant/dashboard#staff_balance", :as => :staff_balance
    post "staff_balance", :to => "tenant/dashboard#staff_balance"

    get "calendar", :to => "tenant/dashboard#calendar", :as => :calendar

    get "staff_calendar", :to => "tenant/dashboard#staff_calendar", :as => :staff_calendar
    post "staff_calendar", :to => "tenant/dashboard#staff_calendar"

    get "heatmap", :to => "tenant/dashboard#heatmap", :as => :heatmap
    post "heatmap", :to => "tenant/dashboard#heatmap"

    get "help", :to => "tenant/dashboard#help", :as => :help
    
    # profile
    get "activate", :to => "tenant/profile#activate", :as => :activate
    put "activate", :to => "tenant/profile#setactive", :as => :activate
    
    get "profile", :to => "tenant/profile#edit", :as => :profile
    put "profile", :to => "tenant/profile#update", :as => :update_profile

    # employee leave requests
    get "leave", :to => "tenant/employee_leave_requests#index", :as => :employee_leave_requests
    post "leave", :to => "tenant/employee_leave_requests#index"
    get "leave/new", :to => "tenant/employee_leave_requests#new", :as => :new_employee_leave_request
    post "leave/new", :to => "tenant/employee_leave_requests#create", :as => :create_employee_leave_request

    get "staff_leave_summary", :to => "tenant/dashboard#staff_leave_summary", :as => :staff_leave_summary
    post "staff_leave_summary", :to => "tenant/dashboard#staff_leave_summary"

    # staff leave requests
    get "staff_leave", :to => "tenant/staff_leave_requests#index", :as => :staff_leave_requests
    post "staff_leave", :to => "tenant/staff_leave_requests#index"
    get "staff_leave/new", :to => "tenant/staff_leave_requests#new", :as => :new_staff_leave_request
    post "staff_leave/new", :to => "tenant/staff_leave_requests#create", :as => :create_staff_leave_request

    # both employee and staff leave requests
    resources :leave_requests, :path => '/leave', :module => 'tenant', :except => [:index, :new, :create, :edit, :update, :destroy] do
      member do
        get 'amend'
        put 'confirm'
        put 'approve'
        put 'decline'
        put 'cancel'
        put 'reinstate'
        put 'update_constraints'
        put 'update_document'
        delete 'remove_document'
      end
    end

    get "leave_balance", :to => "tenant/leave_requests#balance", :as => :leave_balance

    # data feeds
    get "calendar_entries_feed(.:format)", :to => "tenant/data_feeds#calendar_entries", :as => :calendar_entries_feed
    get "leave_requests_feed(.:format)", :to => "tenant/data_feeds#leave_requests", :as => :leave_requests_feed

    scope "account" do

      get "edit", :to => "tenant/account#edit", :as => :edit_account
      put "edit", :to => "tenant/account#update", :as => :update_account

      get "policies", :to => "tenant/leave_types#edit", :as => :edit_leave_types
      put "policies", :to => "tenant/leave_types#update", :as => :update_leave_types

      resources :locations, :module => 'tenant'
      resources :departments, :module => 'tenant'
      
      resources :employees, :module => 'tenant' do
        collection do
          get 'filtered'
          post 'filtered'
        end

        member do
          put 'deactivate'
          put 'reactivate'
        end
      end

      get "employee_balance(.:format)", :to => "tenant/employees#balance", :as => :employee_balance

      resources :bulk_uploads, :module => 'tenant', :except => [:index] do
        member do
          get 'download'
        end
        get 'template', :on => :collection, :as => :template
        get 'records', :to => 'bulk_upload_stages#index', :as => :records
        put 'records', :to => 'bulk_upload_stages#index'
      end
      
      get "/", :to => "tenant/account#index", :as => :account

    end

    get "/", :to => "tenant/dashboard#index", :as => :dashboard

  end

  root :to => "home#index"

end

app/views/shared/_flash.html.erb
<!-- TODO: add js to hide and show (slide down/up transition) and add close button -->
<% if flash.count > 0 %>
<div class="notices box_radius">
  <% flash.each do |type, msg| %>
    <%= content_tag :div, msg, :class => "flash flash_#{type}" %>
  <% end %>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div style="text-align: center;">
  <%= link_to "Home", root_path %> |
  <%= link_to "Pricing", home_subscriptions_path %> |
  <%= link_to "Terms", home_terms_path %> |
  <%= link_to "Privacy", home_privacy_path %> |
  <%= link_to "Partners", home_partner_path %> |
  <%= link_to "Contact", home_contact_path %>
</div>
<div style="text-align: center; padding-top: 8px;">
  <small>Copyright &copy; <%= Date.today.year %> <%= AppConfig.company_name %></small>
</div>

app/views/shared/_header.html.erb
<div class="row">
  <div class="column grid_10">
    <h2 class="title_bar_title"><%= AppConfig.title + (content_for?(:title) ? ' > ' + yield(:title) : '') %></h2>
  </div>
  <div class="column grid_2">
    <%= link_to image_tag('app_logo.png'), root_path %>    
  </div>
</div>

app/views/shared/_html_head.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
  <title><%= content_for?(:title) ? AppConfig.title + ' - ' + yield(:title) : AppConfig.title %></title>
  <meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="<%= AppConfig.meta_description %>" />
  <meta name="keywords" content="<%= AppConfig.meta_keywords %>" />
  <meta name="robots" content="<%= content_for?(:robots) ? yield(:robots) : 'noindex' %>" />
  <link href='https://fonts.googleapis.com/css?family=Ubuntu:regular,italic,bold&subset=cyrillic,latin' rel='stylesheet' type='text/css' />
  <!--[if lt IE 9]>
  <%= javascript_include_tag 'html5' %>
  <link rel="stylesheet" type="text/css" href="ie-table.css" />
  <![endif]-->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="shortcut icon" href="/favicon.ico">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults, 'google_analytics' %>
  <%= csrf_meta_tag %>
  <%= yield(:head) %>
</head>

app/views/shared/_menu.html.erb
<div class="menu_bar menu_bar_left">
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Pricing", home_subscriptions_path %></li>
    <li><%= link_to "Terms", home_terms_path %></li>
    <li><%= link_to "Contact", home_contact_path %></li>
  </ul>
</div>
<div class="menu_bar menu_bar_right">
  <ul>
    
    <% if Rails.env.development? || AppConfig.subdomain == 'test' %>
      <li style="padding-top: 4px;">
        <select id="select_account" style="width: 260px;">
          <option>Select Account</option>
          <%= options_for_select(
            Account.select {|account| !account.default_admin.nil? }.collect {|account| 
              [
                "#{account.subdomain} (#{account.default_admin.user_name})", 
                impersonate_path(account.default_admin.to_param)
              ] 
          }) %>
        </select>
      </li>

      <script type="text/javascript">
        $('#select_account').change(function(){
          window.location = $('#select_account').val();
        });
      </script>

    <% end %>

  </ul>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
  Signed in as <%= link_to current_employee, profile_path, :title => "Your user name is '#{current_employee.user_name}'" %>.

  <br/>
  <div style="font-size: 8pt;"><%= current_employee.role.titleize %> permissions</div>
</div>