config/routes.rb
HumanFaktor::Application.routes.draw do

  ###
  # routes for base
  #
  
  # NNB: be sure to update the subdomain validator options for account to 
  #      include these paths as restricted names

  get "contact", :to => 'home#contact', :as => :home_contact
  get "features", :to => 'home#features', :as => :home_features
  get "subscriptions", :to => 'home#subscriptions', :as => :home_subscriptions
  get "terms", :to => 'home#terms', :as => :home_terms
  get "privacy", :to => 'home#privacy', :as => :home_privacy
  get "partner", :to => 'home#partner', :as => :home_partner
  get "sign_in", :to => 'home#sign_in', :as => :home_sign_in

  get "demo_request", :to => 'demo_requests#new', :as => :new_demo_request
  post "demo_request", :to => 'demo_requests#create', :as => :create_demo_request

  get "registrations/new", :to => 'registrations#new', :as => :new_account_registration
  post "registrations", :to => 'registrations#create', :as => :create_account_registration
  get "registrations/:id", :to => 'registrations#show', :as => :account_registration
  get "registrations/:id/query/:started(.:format)", :to => 'registrations#query', :as => :query_account_registration

  ###
  # routes for tenant administration
  #

  scope 'admin' do

    devise_for :tenant_admins, :path => "" do
      # TODO: additional configuration for devise
    end

    get "impersonate/:id", :to => 'tenant_admin#impersonate', :as => :impersonate
    get ":id", :to => 'tenant_admin#show', :as => :show_account
    get "/", :to => 'tenant_admin#index', :as => :tenant_admin

  end

  ###
  # routes for tenant
  #

  # NOTE: this part of the route is "globbed" and there are some issues 
  #       in Rails when there are nested routes, so a `:tenant => current_account.subdomain` option 
  #       is required for url helpers when constructing paths
  scope "*tenant" do

    get "setup", :to => "tenant/account_setup#edit", :as => :account_setup
    put "setup", :to => "tenant/account_setup#update", :as => :update_account_setup

    devise_for :employees, :path => "" do
      # TODO: additional configuration for devise
    end

    get "welcome", :to => "tenant/dashboard#welcome", :as => :welcome

    # dashboard
    get "balance", :to => "tenant/dashboard#balance", :as => :balance

    get "staff_balance", :to => "tenant/dashboard#staff_balance", :as => :staff_balance
    post "staff_balance", :to => "tenant/dashboard#staff_balance"

    get "calendar", :to => "tenant/dashboard#calendar", :as => :calendar

    get "staff_calendar", :to => "tenant/dashboard#staff_calendar", :as => :staff_calendar
    post "staff_calendar", :to => "tenant/dashboard#staff_calendar"

    get "heatmap", :to => "tenant/dashboard#heatmap", :as => :heatmap
    post "heatmap", :to => "tenant/dashboard#heatmap"

    get "help", :to => "tenant/dashboard#help", :as => :help
    
    # profile
    get "activate", :to => "tenant/profile#activate", :as => :activate
    put "activate", :to => "tenant/profile#setactive", :as => :activate
    
    get "profile", :to => "tenant/profile#edit", :as => :profile
    put "profile", :to => "tenant/profile#update", :as => :update_profile

    # employee leave requests
    get "leave", :to => "tenant/employee_leave_requests#index", :as => :employee_leave_requests
    post "leave", :to => "tenant/employee_leave_requests#index"
    get "leave/new", :to => "tenant/employee_leave_requests#new", :as => :new_employee_leave_request
    post "leave/new", :to => "tenant/employee_leave_requests#create", :as => :create_employee_leave_request

    get "staff_leave_summary", :to => "tenant/dashboard#staff_leave_summary", :as => :staff_leave_summary
    post "staff_leave_summary", :to => "tenant/dashboard#staff_leave_summary"

    # staff leave requests
    get "staff_leave", :to => "tenant/staff_leave_requests#index", :as => :staff_leave_requests
    post "staff_leave", :to => "tenant/staff_leave_requests#index"
    get "staff_leave/new", :to => "tenant/staff_leave_requests#new", :as => :new_staff_leave_request
    post "staff_leave/new", :to => "tenant/staff_leave_requests#create", :as => :create_staff_leave_request

    # both employee and staff leave requests
    resources :leave_requests, :path => '/leave', :module => 'tenant', :except => [:index, :new, :create, :edit, :update, :destroy] do
      member do
        get 'amend'
        put 'confirm'
        put 'approve'
        put 'decline'
        put 'cancel'
        put 'reinstate'
        put 'update_constraints'
        put 'update_document'
        delete 'remove_document'
      end
    end

    get "leave_balance", :to => "tenant/leave_requests#balance", :as => :leave_balance

    # data feeds
    get "calendar_entries_feed(.:format)", :to => "tenant/data_feeds#calendar_entries", :as => :calendar_entries_feed
    get "leave_requests_feed(.:format)", :to => "tenant/data_feeds#leave_requests", :as => :leave_requests_feed

    scope "account" do

      get "edit", :to => "tenant/account#edit", :as => :edit_account
      put "edit", :to => "tenant/account#update", :as => :update_account

      get "policies", :to => "tenant/leave_types#edit", :as => :edit_leave_types
      put "policies", :to => "tenant/leave_types#update", :as => :update_leave_types

      resources :locations, :module => 'tenant'
      resources :departments, :module => 'tenant'
      
      resources :employees, :module => 'tenant' do
        collection do
          get 'filtered'
          post 'filtered'
        end

        member do
          put 'deactivate'
          put 'reactivate'
        end
      end

      get "employee_balance(.:format)", :to => "tenant/employees#balance", :as => :employee_balance

      resources :bulk_uploads, :module => 'tenant', :except => [:index] do
        member do
          get 'download'
        end
        get 'template', :on => :collection, :as => :template
        get 'records', :to => 'bulk_upload_stages#index', :as => :records
        put 'records', :to => 'bulk_upload_stages#index'
      end
      
      get "/", :to => "tenant/account#index", :as => :account

    end

    get "/", :to => "tenant/dashboard#index", :as => :dashboard

  end

  root :to => "home#index"

end

app/controllers/home_controller.rb
require 'geoip'

class HomeController < ApplicationController

  skip_before_filter :ensure_account

  def index
  end

  def contact
  end

  def terms
  end
  
  def privacy
  end

  def features
  end

  def subscriptions
    
    @default_subscription = Subscription.default
    @subscriptions = Subscription.active.where('price > 0')

    # use the country parameter
    if params[:country].present?
      @country = Country.by_iso_code(params[:country]) || Country.by_iso_code('za')
    else

      # see http://www.maxmind.com/app/country and http://www.maxmind.com/app/ruby for more details

      # use Geo IP to figure out the country from the IP address
      geoinf = GeoIP.new(File.join(::Rails.root, 'db', 'geoip.dat')).country(request.remote_ip)

      #
      # For now, only interested in whether the request is from South Africa
      #  otherwise, we use USA as the country
      #
      @country = (geoinf.country_code2 == "ZA") ? 
                    Country.by_iso_code('za') :
                    Country.by_iso_code('us') 

    end

  end

  def partner
  end

  def sign_in
  end
  
end

app/views/home/contact.html.erb
<% title "Contact Details" %>

<p>Send an email to <%= mail_to AppConfig.info_email %>.</p>

app/views/home/features.html.erb
<% title "Features" %>

<ul>
  <li>Simple, intuitive and efficient leave management service</li>
  <li>Full leave application, approval, rejection workflow</li>
  <li>E-mail notification of entire application process</li>
  <li>Dashboards for effective management information</li>
  <li>Heat maps to identify potential staff issues </li>
  <li>
    Cost effective –Pay per employee.
    <ul>
      <li>No hardware costs,</li>
      <li>No software costs,</li>
      <li>No installation costs,</li>
      <li>No hidden costs.</li>
    </ul>
  </li>
</ul>

app/views/home/index.html.erb
<% robots "index, follow" %>

<h2 style="text-align: center; margin: 20px;">
  The online employee leave management solution!
</h2>

<div>

  <div style="height: 220px; padding: 0 160px 0 160px;">

    <div style="float: left; margin: 8px; width: 280px;">
      <div style="padding: 12px; text-align: center; height: 166px;" class="nice_box <%= session[:visited] ? '' : 'make_prominant' %>">
        <div>
          <%= link_to image_tag('../images/play.png'), dashboard_path(:tenant => 'demo', :auth_token => auth_token), :target => '_blank' %>
        </div>
        <p>
          Give it a try now! <br/> 
          No need to create an account!
        </p>
        <p>
          Click here for a <%= link_to 'Demo', dashboard_path(:tenant => 'demo', :auth_token => auth_token), :target => '_blank' %></p>
        </p>
      </div>
    </div>  

    <div style="float: right; margin: 8px; width: 280px;">
      <div style="padding: 12px; text-align: center; height: 166px;" class="nice_box <%= session[:visited] ? 'make_prominant' : '' %>">
        <div>
          <%= link_to image_tag('../images/start.png'), new_account_registration_path() %>
        </div>
        <p>
          Get started Today! <br/> 
        </p>
        <p>
          Click here for a <%= link_to 'Free Trial', new_account_registration_path() %></p>
        </p>
      </div>
    </div>  
  </div>

  <div style="padding: 0 160px 20px 160px;">

    <ul class="features">
      <li class="nice_box simple">Simple, intuitive and efficient leave management</li>
      <li class="nice_box workflow">Full leave application, approval, rejection workflow</li>
      <li class="nice_box email">E-mail notification of entire application process</li>
      <li class="nice_box dashboard">Dashboards for effective management information</li>
      <li class="nice_box heatmap">Heat maps to identify potential staff issues </li>
    </ul>

  </div>

</div>

  

app/views/home/partner.html.erb
<% title "Affiliate Partner Program" %>

<p>Typical partners include;</p>

<ul>
  <li>HR consultants</li>
  <li>Software vendors</li>
  <li>General business consultants</li>
  <li>Other online service providers</li>
</ul>

<p>
If you are positioned to market Human-Faktor leave management then please contact us for further information.
</p>

<p>Send an email to <%= mail_to 'info@human-faktor.com' %></p>

app/views/home/privacy.html.erb
<h1><%= AppConfig.title %></h1>
<em>Last Updated on 16 August, 2011.</em>

<div id="legal">

  <h2>PRIVACY AGREEMENT</h2>

  <p><%= AppConfig.company_name %> requires certain personal information to be provided by it&#39;s clients in order to operate 
  the functionality of the <%= AppConfig.title %> service.</p> 

  <p>This information includes the following, but is not limited to; individuals names, company names, contact details, 
  company position and leave entitlement.</p>

  <p>Any Personal Information collected shall also form part of <%= AppConfig.company_name %> database of clients and/or
  partners, as the case may be.</p> 

  <p><%= AppConfig.company_name %> shall rely on and use such personal information to communicate with its clients regarding 
  company updates and/or our product and service offerings.</p>

  <p>Personal information collected by <%= AppConfig.company_name %> may be stored and processed in South Africa or in any
  other country in which <%= AppConfig.company_name %> or its subsidiaries maintain facilities.</p>

  <p><%= AppConfig.company_name %> uses third party vendors and hosting partners to provide the necessary hardware, software, 
  networking, storage, and related technology required to run our services. Although <%= AppConfig.company_name %> owns 
  the code, databases, and all rights to the <%= AppConfig.product_group %> applications, you retain all rights to your data.</p>

  <p><%= AppConfig.company_name %> shall take all necessary measures to protect the confidentiality of any Personal 
  Information collected from its clients and partners. It shall also ensure that any Personal Information collected 
  shall be utilized by it or by its subsidiaries or agents strictly for business purposes.</p>

  <p>Except for disclosure to its subsidiaries or agents, <%= AppConfig.company_name %> shall not disclose any Personal 
  Information provided by its clients and partners to third parties unless it has obtained the prior consent of the 
  client or partner concerned. In no case shall <%= AppConfig.company_name %> sell, rent or lease any Personal 
  Information to third parties.</p>

  <h2>PRIVACY INQUIRIES OR COMPLAINTS</h2>

  <p><%= AppConfig.company_name %> commits to resolve complaints about your privacy and our collection or use of your 
  personal information. Any inquiries or complaints regarding this privacy policy should be addressed to 
  <%= mail_to AppConfig.info_email, AppConfig.info_email %>.</p>

</div>

app/views/home/sign_in.html.erb
<% title "Account Sign In" %>

<div style="text-align: center;">

<p>When you registered we sent you a welcome email with your <strong><%= AppConfig.title %></strong> URL.</p>
<p>The URL will have your <em title="Or possibly an abbreviation of your company name">company name</em> in the path.</p>

<p>It should look something like:</p>
<h3 style="margin: 30px;"><%= AppConfig.scheme %>://<%= "#{AppConfig.subdomain}.#{AppConfig.domain}" %>/<em>companyname</em></h3>

<p>Try typing the URL with your <em>company name</em> in your browser address bar.</p>
<p>Otherwise, send an email to <%= mail_to AppConfig.support_email, AppConfig.support_email, :subject => "#{AppConfig.title} Support - Forgotten Company Name" %> so we help figure out your URL.</p>

</div>

app/views/home/subscriptions.html.erb
<% title "Pricing" %>

<%

  # HACK!!! Assumes that the subscriptions stored in the database 
  # "align" via the max employees and duration

  subscriptions = [
    ['Small', 25], 
    ['Small-Medium', 50], 
    ['Medium', 100], 
    ['Medium-Large', 150],
    ['Large', 300],
    ['Enterprise', 500],
    ['Enterprise+', 1000]
  ]

  currency_symbol = @country.currency_symbol || 'R'
  currency = @country.currency_code || 'ZAR'

%>

<table class="table_grid">
  <tr class="no_hover">
    <th>Subscription Plan</th>
    
    <% for subscription in subscriptions %>
      <th><%= subscription[0] %></th>
    <% end %>
    
  </tr>
  <tr class="no_hover">
    <td>Max Employees</td>
    
    <% for subscription in subscriptions %>
      <td width="90px">
        <%= subscription[1] %>
      </td>
    <% end %>
    
  </tr>
  <tr class="no_hover">
    <td>
      <div>Monthly Price*</div>
      <small>Paid Monthly</small>
    </td>

    <% for subscription in subscriptions %>
      <td>
        <%= currency_symbol %> <%= number_with_delimiter(@subscriptions.where(:max_employees => subscription[1], :duration => 1).first.price_for(@country).to_i) %>
      </td>
    <% end %>
  
  </tr>

  <tr class="no_hover">
    <td>
      <div>1 Year Price*</div>
      <small>Paid Annually</small>
    </td>

    <% for subscription in subscriptions %>
      <td>
        <%= currency_symbol %> <%= number_with_delimiter(@subscriptions.where(:max_employees => subscription[1], :duration => 12).first.price_for(@country).to_i) %>
      </td>
    <% end %>
  
  </tr>

  <tr class="no_hover">
    <td>
      <div>3 Year Price*</div>
      <small>Paid Annually</small>
    </td>

    <% for subscription in subscriptions %>
      <td>
        <%= currency_symbol %> <%= number_with_delimiter(@subscriptions.where(:max_employees => subscription[1], :duration => 36).first.price_for(@country).to_i) %>
      </td>
    <% end %>
  
  </tr>

  <tr class="no_hover">
    <td>
    </td>

    <% for subscription in subscriptions %>
      <td>
        <div class="button">
          <%= link_to 'Sign Up', new_account_registration_path(:subscription => subscription[1]) %>
        </div>
      </td>
    <% end %>
  
  </tr>

</table>

<div style="height: 32px">
  <div style="margin-top: 8px; float: left;">
    <%= link_to 'Sign Up', new_account_registration_path() %> for a Free Trial for <%= @default_subscription.max_employees %> employees.
  </div>

  <div style="margin-top: 8px; float: right; text-align: right;">
    <i>* All prices given in <%= currency %> currency.</i>
  </div>
</div>

<div class="clearfix"></div>

<style type="text/css">

  tr {
    height: 60px;
  }

  th {
    text-align: center; 
    border-right: 1px solid #C0C0C0;
  }

  td {
    text-align: center; 
    border-right: 1px solid #C0C0C0;
  }

  td small {
    font-size: 8pt;
  }
  
  th:nth-child(even) {
    background-color: #E0E0E0;
  }

  td:nth-child(even) {
    background-color: #E0E0E0;
  }
  
  th:first-child {
    text-align: left;
    border-right: 1px solid #C0C0C0;
    padding-left: 8px;
  }
  
  td:first-child {
    text-align: left;
    border-right: 1px solid #C0C0C0;
    padding-left: 14px;
  }

  th:last-child {
    border-right: none !important;
  }

  td:last-child {
    border-right: none !important;
  }

</style>