config/routes.rb
HumanFaktor::Application.routes.draw do

  ###
  # routes for base
  #
  
  # NNB: be sure to update the subdomain validator options for account to 
  #      include these paths as restricted names

  get "contact", :to => 'home#contact', :as => :home_contact
  get "features", :to => 'home#features', :as => :home_features
  get "subscriptions", :to => 'home#subscriptions', :as => :home_subscriptions
  get "terms", :to => 'home#terms', :as => :home_terms
  get "privacy", :to => 'home#privacy', :as => :home_privacy
  get "partner", :to => 'home#partner', :as => :home_partner
  get "sign_in", :to => 'home#sign_in', :as => :home_sign_in

  get "demo_request", :to => 'demo_requests#new', :as => :new_demo_request
  post "demo_request", :to => 'demo_requests#create', :as => :create_demo_request

  get "registrations/new", :to => 'registrations#new', :as => :new_account_registration
  post "registrations", :to => 'registrations#create', :as => :create_account_registration
  get "registrations/:id", :to => 'registrations#show', :as => :account_registration
  get "registrations/:id/query/:started(.:format)", :to => 'registrations#query', :as => :query_account_registration

  ###
  # routes for tenant administration
  #

  scope 'admin' do

    devise_for :tenant_admins, :path => "" do
      # TODO: additional configuration for devise
    end

    get "impersonate/:id", :to => 'tenant_admin#impersonate', :as => :impersonate
    get ":id", :to => 'tenant_admin#show', :as => :show_account
    get "/", :to => 'tenant_admin#index', :as => :tenant_admin

  end

  ###
  # routes for tenant
  #

  # NOTE: this part of the route is "globbed" and there are some issues 
  #       in Rails when there are nested routes, so a `:tenant => current_account.subdomain` option 
  #       is required for url helpers when constructing paths
  scope "*tenant" do

    get "setup", :to => "tenant/account_setup#edit", :as => :account_setup
    put "setup", :to => "tenant/account_setup#update", :as => :update_account_setup

    devise_for :employees, :path => "" do
      # TODO: additional configuration for devise
    end

    get "welcome", :to => "tenant/dashboard#welcome", :as => :welcome

    # dashboard
    get "balance", :to => "tenant/dashboard#balance", :as => :balance

    get "staff_balance", :to => "tenant/dashboard#staff_balance", :as => :staff_balance
    post "staff_balance", :to => "tenant/dashboard#staff_balance"

    get "calendar", :to => "tenant/dashboard#calendar", :as => :calendar

    get "staff_calendar", :to => "tenant/dashboard#staff_calendar", :as => :staff_calendar
    post "staff_calendar", :to => "tenant/dashboard#staff_calendar"

    get "heatmap", :to => "tenant/dashboard#heatmap", :as => :heatmap
    post "heatmap", :to => "tenant/dashboard#heatmap"

    get "help", :to => "tenant/dashboard#help", :as => :help
    
    # profile
    get "activate", :to => "tenant/profile#activate", :as => :activate
    put "activate", :to => "tenant/profile#setactive", :as => :activate
    
    get "profile", :to => "tenant/profile#edit", :as => :profile
    put "profile", :to => "tenant/profile#update", :as => :update_profile

    # employee leave requests
    get "leave", :to => "tenant/employee_leave_requests#index", :as => :employee_leave_requests
    post "leave", :to => "tenant/employee_leave_requests#index"
    get "leave/new", :to => "tenant/employee_leave_requests#new", :as => :new_employee_leave_request
    post "leave/new", :to => "tenant/employee_leave_requests#create", :as => :create_employee_leave_request

    get "staff_leave_summary", :to => "tenant/dashboard#staff_leave_summary", :as => :staff_leave_summary
    post "staff_leave_summary", :to => "tenant/dashboard#staff_leave_summary"

    # staff leave requests
    get "staff_leave", :to => "tenant/staff_leave_requests#index", :as => :staff_leave_requests
    post "staff_leave", :to => "tenant/staff_leave_requests#index"
    get "staff_leave/new", :to => "tenant/staff_leave_requests#new", :as => :new_staff_leave_request
    post "staff_leave/new", :to => "tenant/staff_leave_requests#create", :as => :create_staff_leave_request

    # both employee and staff leave requests
    resources :leave_requests, :path => '/leave', :module => 'tenant', :except => [:index, :new, :create, :edit, :update, :destroy] do
      member do
        get 'amend'
        put 'confirm'
        put 'approve'
        put 'decline'
        put 'cancel'
        put 'reinstate'
        put 'update_constraints'
        put 'update_document'
        delete 'remove_document'
      end
    end

    get "leave_balance", :to => "tenant/leave_requests#balance", :as => :leave_balance

    # data feeds
    get "calendar_entries_feed(.:format)", :to => "tenant/data_feeds#calendar_entries", :as => :calendar_entries_feed
    get "leave_requests_feed(.:format)", :to => "tenant/data_feeds#leave_requests", :as => :leave_requests_feed

    scope "account" do

      get "edit", :to => "tenant/account#edit", :as => :edit_account
      put "edit", :to => "tenant/account#update", :as => :update_account

      get "policies", :to => "tenant/leave_types#edit", :as => :edit_leave_types
      put "policies", :to => "tenant/leave_types#update", :as => :update_leave_types

      resources :locations, :module => 'tenant'
      resources :departments, :module => 'tenant'
      
      resources :employees, :module => 'tenant' do
        collection do
          get 'filtered'
          post 'filtered'
        end

        member do
          put 'deactivate'
          put 'reactivate'
        end
      end

      get "employee_balance(.:format)", :to => "tenant/employees#balance", :as => :employee_balance

      resources :bulk_uploads, :module => 'tenant', :except => [:index] do
        member do
          get 'download'
        end
        get 'template', :on => :collection, :as => :template
        get 'records', :to => 'bulk_upload_stages#index', :as => :records
        put 'records', :to => 'bulk_upload_stages#index'
      end
      
      get "/", :to => "tenant/account#index", :as => :account

    end

    get "/", :to => "tenant/dashboard#index", :as => :dashboard

  end

  root :to => "home#index"

end

app/controllers/tenant/account_controller.rb
module Tenant
  class AccountController < AdminController
    
    def index
    end
    
    def edit
      @account = current_account
    end

    def update
      @account = current_account
      
      respond_to do |format|
        if @account.update_attributes(params[:account])
          format.html { redirect_to(edit_account_path, :notice => 'Account was successfully updated.') }
        else
          format.html { render :action => "edit" }
        end
      end
    end
    
  end
end

app/controllers/tenant/account_setup_controller.rb
require 'date'

module Tenant
  class AccountSetupController < TenantController

    skip_before_filter :check_account_active, :authenticate_employee!, :check_employee

    def initialize
      self.partials_path = 'admin'
      super
    end
    
    def edit
      @account = current_account
      
      # setup already?
      redirect_to dashboard_url and return if @account.active?
      
      registration = @account.registration
      @account_setup = AccountSetup.new().tap do |setup|
        setup.admin_first_name = registration.first_name
        setup.admin_last_name = registration.last_name
        setup.admin_user_name = registration.user_name
        setup.admin_email = registration.email
        setup.fixed_daily_hours = @account.fixed_daily_hours
        setup.leave_cycle_start_date = Date.new(Date.today.year, 1, 1)

        LeaveType.for_each_leave_type_name do |leave_type_name|
          leave_type = @account.send("leave_type_#{leave_type_name}")
          setup.send("#{leave_type_name}_leave_allowance=", leave_type.cycle_days_allowance)
        end

        setup.auth_token = @account.auth_token
        setup.auth_token_confirmation = params[:token] if @account.auth_token == params[:token]
      end
    end
    
    def update
      @account = current_account

      setup_params = params[:account_setup]
      
      # fix up the date
      setup_params[:leave_cycle_start_date] = Date.civil(
        setup_params.delete(:"leave_cycle_start_date(1i)").to_i,
        setup_params.delete(:"leave_cycle_start_date(2i)").to_i,
        setup_params.delete(:"leave_cycle_start_date(3i)").to_i
      ) unless setup_params[:leave_cycle_start_date].present?

      @account_setup = AccountSetup.new(setup_params)
      @account_setup.auth_token = @account.auth_token
      
      respond_to do |format|
        if @account_setup.save(@account) 
          sign_in(:employee, @account.employees.first)
          format.html { redirect_to(welcome_url, :notice => 'Account successfully setup.') }
        else
          format.html { render :action => "edit" }
        end
      end
    end

  end
end

app/controllers/tenant/admin_controller.rb
module Tenant
  class AdminController < TenantController

    # must be an administrator
    before_filter :ensure_admin
    
    def initialize
      self.partials_path = 'admin'
      super
    end

  end
end

app/controllers/tenant/bulk_upload_stages_controller.rb
module Tenant
  class BulkUploadStagesController < AdminController

    def index
      @bulk_upload = current_account.bulk_uploads.find(params[:bulk_upload_id])
      case params[:status]
        when 'valid'
          @records = @bulk_upload.records.where(:selected => true).page(params[:page])
        when 'errors'
          @records = @bulk_upload.records.where(:selected => false).page(params[:page])
        else
          @records = @bulk_upload.records.page(params[:page])
      end
    end

  end
end

app/controllers/tenant/bulk_uploads_controller.rb
module Tenant
  class BulkUploadsController < AdminController
    
    def new
      @bulk_upload = current_account.bulk_uploads.build()

      respond_to do |format|
        format.html # new.html.erb
      end
    end
    
    def create
      @bulk_upload = current_account.bulk_uploads.build(params[:bulk_upload])
      @bulk_upload.uploaded_by = current_employee  # will always be an admin
    
      respond_to do |format|
        if @bulk_upload.save
          format.html { redirect_to bulk_upload_url(@bulk_upload, :tenant => current_account.subdomain), 
                          :notice => 'Successfully created bulk upload. Please wait while the file is processed.' }
        else
          format.html { render :new }
        end
      end
    end
    
    def show
      @bulk_upload = current_account.bulk_uploads.find(params[:id])
      redirect_to edit_bulk_upload_url(@bulk_upload, :tenant => current_account.subdomain) if @bulk_upload.status_staged?
    end
    
    def edit
      @bulk_upload = current_account.bulk_uploads.find(params[:id])
    end
    
    def update
      @bulk_upload = current_account.bulk_uploads.find(params[:id])

      respond_to do |format|
        if @bulk_upload.set_as_accepted()
          format.html { redirect_to bulk_upload_url(@bulk_upload, :tenant => current_account.subdomain), 
                          :notice => 'Successfully queued bulk upload for import. Please wait while the data is imported.' }
        else
          format.html { render :edit }
        end
      end
    end
    
    def destroy
      @bulk_upload = current_account.bulk_uploads.find(params[:id])
      @bulk_upload.destroy
      
      redirect_to account_url, :notice => 'Successfully deleted bulk upload.'
    end
    
    def template
    end
    
    def download
      @bulk_upload = current_account.bulk_uploads.find(params[:id])
      redirect_to @bulk_upload.authenticated_url()
    end
    
  end
end

app/controllers/tenant/dashboard_controller.rb
module Tenant
  class DashboardController < TenantController
    layout 'dashboard'
    
    before_filter :handle_demo_request_trackback

    def index
      # create a holder for all the data instead of separate variables here
      @dashboard = DashboardData.new(current_account, current_employee)
    end
    
    def welcome
    end

    def balance
      @employee = params[:employee].present? ?
                    current_account.employees.find_by_identifier(params[:employee]) :
                    current_employee

      # permission check
      if @employee != current_employee && !current_employee.is_manager_of?(@employee) 
        redirect_to dashboard_url and return false
      end

      @date_as_at = safe_parse_date(params[:as_at], Date.today)
      @account = current_account
    
      # get leave types, filtered by the gender of the employee
      @leave_types = current_account.leave_types.select {|leave_type| 
        !(leave_type.gender_filter & @employee.gender_filter).empty?
      }
      
    end

    # GET & POST
    def staff_balance
      redirect_to balance_url if current_employee.is_employee?

      @leave_types = current_account.leave_types

      filter_params = params[:staff_balance_enquiry] || {}
      @staff_balance = StaffBalanceEnquiry.new(current_account, current_employee).tap do |c|
        c.date_as_at = safe_parse_date(filter_params[:date_as_at], Date.today)
        c.leave_type_id = filter_params[:leave_type_id] if filter_params[:leave_type_id]
        c.filter_by = @filter_by = filter_params[:filter_by] || 'none'
        c.location_id = filter_params[:location_id] || current_employee.location_id
        c.department_id = filter_params[:department_id] || current_employee.department_id
        c.employee_id = filter_params[:employee_id] || current_employee.id
        
        c.valid?
      end

      @employees = Kaminari.paginate_array(@staff_balance.employees).page(params[:page])
      
    end

    def calendar
    end

    # GET & POST
    def staff_calendar
      redirect_to calendar_url if current_employee.is_employee?

      filter_params = params[:staff_calendar_enquiry] || {}
      @staff_calendar = StaffCalendarEnquiry.new(current_account, current_employee).tap do |c|
        c.date_from = safe_parse_date(filter_params[:date_from], leave_cycle_start_date())
        c.date_to = safe_parse_date(filter_params[:date_to], leave_cycle_end_date())
        c.filter_by = @filter_by = filter_params[:filter_by] || 'none'
        c.location_id = filter_params[:location_id] || current_employee.location_id
        c.department_id = filter_params[:department_id] || current_employee.department_id
        c.employee_id = filter_params[:employee_id] || current_employee.id
        
        c.valid?
      end

    end
    
    # GET & POST
    def staff_leave_summary
      redirect_to dashboard_url if current_employee.is_employee?

      @leave_types = current_account.leave_types

      filter_params = params[:staff_leave_summary_enquiry] || {}
      @filter = StaffLeaveSummaryEnquiry.new(current_account, current_employee).tap do |c|
        c.date_from = safe_parse_date(filter_params[:date_from], leave_cycle_start_date())
        c.date_to = safe_parse_date(filter_params[:date_to], leave_cycle_end_date())
        c.filter_by = @filter_by = filter_params[:filter_by] || 'none'
        c.location_id = filter_params[:location_id] || current_employee.location_id
        c.department_id = filter_params[:department_id] || current_employee.department_id
        c.employee_id = filter_params[:employee_id] || current_employee.id
        
        c.valid?
      end

      @employees = Kaminari.paginate_array(@filter.employees).page(params[:page])

    end

    # GET & POST
    def heatmap
      redirect_to dashboard_url unless current_employee.is_admin? || current_employee.is_manager?
      
      filter_params = params[:heat_map_enquiry] || {}
      @heat_map = HeatMapEnquiry.new(current_account, current_employee).tap do |c| 
        c.enquiry = filter_params[:enquiry] if filter_params[:enquiry]
        
        c.date_from = safe_parse_date(filter_params[:date_from], leave_cycle_start_date())
        c.date_to = safe_parse_date(filter_params[:date_to], leave_cycle_end_date())
        c.filter_by = @filter_by = filter_params[:filter_by] || 'none'
        c.location_id = filter_params[:location_id] || current_employee.location_id
        c.department_id = filter_params[:department_id] || current_employee.department_id
        c.employee_id = filter_params[:employee_id] || current_employee.id
        
        c.valid?
      end
      
    end
    
    def help
    end

  private

    def handle_demo_request_trackback
      unless params[:r].nil?
        demo_request = DemoRequest.find(params[:r])
        demo_request.update_attributes!(:trackback => true) if demo_request
      end
    rescue
      # ignore any errors!
      true
    end

  end
end

app/controllers/tenant/data_feeds_controller.rb
module Tenant
  class DataFeedsController < TenantController

    # used in calendar control
    def calendar_entries
      from_date = Time.at(params[:start].to_i).to_date
      to_date = Time.at(params[:end].to_i).to_date

      @calendar_entries = current_account.country.calendar_entries.where(
        ' entry_date BETWEEN :from_date AND :to_date ',
        { :from_date => from_date, :to_date => to_date } 
      )
      
      respond_to do |format|
        format.json # calendar_entries.json.erb
      end
    end
    
    # used in calendar control
    def leave_requests
      from_date = Time.at(params[:start].to_i).to_date
      to_date = Time.at(params[:end].to_i).to_date

      @leave_requests = current_employee.leave_requests.active.where(
        ' (date_from BETWEEN :from_date AND :to_date ) OR ( date_to BETWEEN :from_date AND :to_date ) ',
        { :from_date => from_date, :to_date => to_date } 
      ).order('created_at DESC')
    
      respond_to do |format|
        format.json # leave_requests.json.erb
      end
    end
    
  end
end

app/views/tenant/bulk_uploads/_status_accepted.html.erb
<p class="ajax_working">The bulk upload file has been queued for the final stage of processing, please wait.</p>

<%= render @bulk_upload %>

<p>The progress will be checked automatically. <%= link_to 'Click here', bulk_upload_path(@bulk_upload, :tenant => current_account.subdomain) %> to check manually.</p>

<script type="text/javascript">
  function check_status() {
    window.location = '<%= bulk_upload_path(@bulk_upload, :tenant => current_account.subdomain) %>'  
  }
  window.setTimeout(check_status, 10000);
</script>  

app/views/tenant/bulk_uploads/_status_failed.html.erb
<p>FAILURE: The bulk upload file failed to be applied.</p>

<%= render @bulk_upload %>

<p>Messages:</p>
<pre style="min-height: 200px; max-height: 300px; overflow: auto;">
<%= @bulk_upload.messages %>
</pre>

<p>
  <%= link_to 'Done', account_path %>
</p>

app/views/tenant/bulk_uploads/_status_processed.html.erb
<p>SUCCESS: The bulk upload file has been applied successfully.</p>

<%= render @bulk_upload %>

<p>Messages:</p>
<pre style="min-height: 60px; max-height: 300px; overflow: auto;">
<%= @bulk_upload.messages %>
</pre>

<p>
  <%= link_to 'Done', account_path %>
</p>

app/views/tenant/bulk_uploads/edit.html.erb
<% title "Staff Bulk Upload" %>

<%= render @bulk_upload %>

<p>Please review the following employee data:</p>

<div id="filter" style="margin-bottom: 10px;">
  <%= form_for @bulk_upload, :as => '', :url => bulk_upload_records_path(@bulk_upload, :tenant => current_account.subdomain), :remote => true do |f| %>
    <table width="100%">
      <tr>
        <td width="120px"></td>
        <td width="30px"></td>
        <td class="field"></td>
        <td style="vertical-align: bottom; align: right;">
          <div style="float: right;">
            <%= render_buttonset(:id => 'status') do |builder| %>
              <% builder.add_button("All", :value => 'all', :checked => true) %>
              <% builder.add_button("Valid", :value => 'valid') %>
              <% builder.add_button("Errors", :value => 'errors') %>
            <% end %>
          </div>
        </td>
      </tr>
    </table>
    <div style="display: none;"><%= f.submit %></div>  
  <% end %>
</div>

<div id="paginator" style="float: left;">
</div>

<div style="height: 32px; margin-bottom: 10px;">
  <div id="ajax_working">Loading employee data...</div>
</div>

<table id="employee_data" class="table_grid">
  <thead>
    <tr>
      <th width="20px"></th>
      <th width="25px">Line</th>
      <th>User Name</th>
      <th>Full Name</th>
      <th>Start Date</th>
      <th>Email</th>
      <th>Approver</th>
      <th></th>
    </tr>
  </thead>
  <tbody id="data-rows">
    <tr class="no_hover">
      <td colspan="8">
        <p>Loading employee data...</p>
      </td>
    </tr>
  </tbody>
</table>

<div style="margin-top: 20px; line-height: 24px;">
  <strong>NOTE:</strong> Invalid rows will be skipped during the import phase.
</div>

<div style="margin-top: 20px;" class="clearfix">
  <div style="float: left; width: 190px; height: 35px;">
    <%= form_for @bulk_upload, :url => bulk_upload_path(@bulk_upload, :tenant => current_account.subdomain) do |f| %>
      <%= f.submit 'Import Employees',
                    :disable_with => 'Importing Employees...', 
                    :style => 'width: 186px;',
                    :disabled => @bulk_upload.records.selected.count() == 0 %>
    <% end %>
  </div>
  <div style="float: left; height: 35px; line-height: 35px;">
    or <%= link_to 'cancel', account_path %>
  </div>
</div>

<script type="text/javascript">
  $('#_edit').submit();
  $('#filter input').change(function(){
    $('#ajax_working').css('display', '');
    $('#paginator').css('display', 'none');
    $('#_edit').submit();
  });
  $('#paginator a').live('ajax:before', function(e) { 
    $('#ajax_working').css('display', '');
    $('#paginator').css('display', 'none');
  });
</script>

app/views/tenant/bulk_uploads/new.html.erb
<% title "Staff Bulk Upload" %>

<p>Supply the following to upload staff data.</p>

<p>Download a <%= link_to 'template file', template_bulk_uploads_path(:format => :csv) %> to help get started.</p>

<%= form_for @bulk_upload, :html => { :multipart => true } do |f| %>
  
  <%= error_messages_for @bulk_upload %>

  <div class="field required">
    <div><%= f.label :csv, 'CSV file name' %></div>
    <span><%= f.file_field :csv %></span>
    <span class="field_info">Comma separated values file. Please see the file specification below.</span>
  </div>

  <div class="field">
    <div><%= f.label :comment %></div>
    <span><%= f.text_area :comment %></span>
    <span class="field_info"></span>
  </div>

  <div class="actions">
    <%= f.submit 'Upload', :disable_with => 'Uploading...', :style => 'width: 120px;' %> or <%= link_to 'cancel', account_path %>
  </div>

<% end %>

<div id="bulk_upload_info">

  <h3>Staff Bulk Upload CSV File Specification</h3>

  <p>You can download a <%= link_to 'template file', template_bulk_uploads_path(:format => :csv) %> to help get started.</p>

  <p>The CSV file must contain the following columns:</p>

  <table class="table_grid">
    <thead>
      <tr>
        <th width="300px">Column</th>
        <th width="60px">Required?</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
    
      <tr>
        <td>reference</td>
        <td>Yes</td>
        <td>
          A <strong>unique</strong> reference for the employee. <br /> 
          It can be in any form, such as an identity number or social security number, provided it uniquely identifies the employee.
        </td>
      </tr>
    
      <tr>
        <td>title</td>
        <td></td>
        <td>
          <em>Optionally</em>, the title of the employee. <br />
          E.g. Dr, Prof, Mr, Mrs, Miss etc.
        </td>
      </tr>
    
      <tr>
        <td>first_name</td>
        <td>Yes</td>
        <td>The employee&#39;s first name.</td>
      </tr>
    
      <tr>
        <td>middle_name</td>
        <td></td>
        <td><em>Optionally</em>, The employee&#39;s middle or second name.</td>
      </tr>
    
      <tr>
        <td>last_name</td>
        <td>Yes</td>
        <td>The employee&#39;s last name or surname.</td>
      </tr>
    
      <tr>
        <td>gender</td>
        <td>Yes</td>
        <td>
          The gender of the employee. <br />  
          Valid values are upper case or lower case letters, and include:
          
          <ul>
            <li><strong>M</strong> for male,</li>
            <li><strong>F</strong> for female.</li>
          </ul>
          
        </td>
      </tr>
    
      <tr>
        <td>email</td>
        <td></td>
        <td>
          <em>Optionally</em>, a valid email address.
        </td>
      </tr>
    
      <tr>
        <td>telephone</td>
        <td></td>
        <td><em>Optionally</em>, a telephone number. Any format is acceptable.</td>
      </tr>
    
      <tr>
        <td>telephone_extension</td>
        <td></td>
        <td><em>Optionally</em>, the telephone extension number. Any format is acceptable.</td>
      </tr>
    
      <tr>
        <td>mobile</td>
        <td></td>
        <td><em>Optionally</em>, a cellular or mobile telephone number. Any format is acceptable.</td>
      </tr>
    
      <tr>
        <td>designation</td>
        <td></td>
        <td>
          <em>Optionally</em>, a designation for the employee. <br />
          E.g. Manager, Clerk, Salesperson etc.
        </td>
      </tr>
    
      <tr>
        <td>start_date</td>
        <td>Yes</td>
        <td>
          The employment start date of the employee. <br />
          Must be supplied in the <strong>YYYY/MM/DD</strong> format, where <em>YYYY</em> is the year including the century,
          <em>MM</em> is the month number (1 to 12) and <em>DD</em> is the day number for the respective month.
        </td>
      </tr>
    
      <tr>
        <td>location_name</td>
        <td></td>
        <td>
          <em>Optionally</em>, the office location where the employee is based. <br />
          <strong>NB:</strong> the corresponding <%= link_to 'office location', locations_path %> must exist. <br />
          If blank, will default to <strong><%= current_account.location %></strong>.
        </td>
      </tr>
    
      <tr>
        <td>department_name</td>
        <td></td>
        <td>
          <em>Optionally</em>, the employee&#39;s department. <br />
          <strong>NB:</strong> the corresponding <%= link_to 'department', departments_path %> must exist. <br />
          If blank, will default to <strong><%= current_account.department %></strong>.
        </td>
      </tr>
    
      <tr>
        <td>approver_first_and_last_name</td>
        <td>Yes</td>
        <td>
          The first and last name of the approver for this employee.<br />
          E.g. John Doe<br />
          <strong>NB:</strong> the corresponding <%= link_to 'approver', employees_path %> must exist, or be contained
          in the file being uploaded. <br />
          If blank, then will default to <strong><%= current_employee %></strong>.
        </td>
      </tr>
    
      <tr>
        <td>role</td>
        <td></td>
        <td>
          <em>Optionally</em>, the employee&#39;s role in the system. Defaults to <em>Employee</em>.<br />
          <strong>NB:</strong> must be one of the following: <br />
          <ul>
            <li><cite>Employee</cite> - The default for employees.</li>
            <li><cite>Approver</cite> - Can approve leave of directly linked staff.</li>
            <li><cite>Manager</cite> - Can approve leave of all linked staff in hierarchy.</li>
            <li><cite>Admin</cite> - Can administer the system, and approve leave of any staff member.</li>
          </ul>

        </td>
      </tr>
    
      <tr>
        <td>take_on_balance_as_at</td>
        <td><strong>*</strong></td>
        <td>
          The effective date for the take on balances. <br />
          If given, needs to be in <strong>YYYY/MM/DD</strong> format, where <em>YYYY</em> is the year including the century,
          <em>MM</em> is the month number (1 to 12) and <em>DD</em> is the day number for the respective month. <br />
          <p><strong>*Required</strong> if take on balances are given.</p>
        </td>
      </tr>
    
      <tr>
        <td>annual_leave_take_on</td>
        <td></td>
        <td>
          <em>Optionally</em>, the take on balance for annual leave.<br />
          Defaults to zero if not given or ignored if <em>take_on_balance_as_at</em> is blank.
        </td>
      </tr>
    
      <tr>
        <td>educational_leave_take_on</td>
        <td></td>
        <td>
          <em>Optionally</em>, the take on balance for educational leave.<br />
          Defaults to zero if not given or ignored if <em>take_on_balance_as_at</em> is blank.
        </td>
      </tr>
    
      <tr>
        <td>medical_leave_take_on</td>
        <td></td>
        <td>
          <em>Optionally</em>, the take on balance for medical leave.<br />
          Defaults to zero if not given or ignored if <em>take_on_balance_as_at</em> is blank.
        </td>
      </tr>
    
      <tr>
        <td>compassionate_leave_take_on</td>
        <td></td>
        <td>
          <em>Optionally</em>, the take on balance for compassionate leave.<br />
          Defaults to zero if not given or ignored if <em>take_on_balance_as_at</em> is blank.
        </td>
      </tr>
    
      <tr>
        <td>maternity_leave_take_on</td>
        <td></td>
        <td>
          <em>Optionally</em>, the take on balance for maternity leave.<br />
          Defaults to zero if not given or ignored if <em>take_on_balance_as_at</em> is blank.
        </td>
      </tr>
    
    </tbody>

  </table>

</div>