config/routes.rb
HumanFaktor::Application.routes.draw do

  ###
  # routes for base
  #
  
  # NNB: be sure to update the subdomain validator options for account to 
  #      include these paths as restricted names

  get "contact", :to => 'home#contact', :as => :home_contact
  get "features", :to => 'home#features', :as => :home_features
  get "subscriptions", :to => 'home#subscriptions', :as => :home_subscriptions
  get "terms", :to => 'home#terms', :as => :home_terms
  get "privacy", :to => 'home#privacy', :as => :home_privacy
  get "partner", :to => 'home#partner', :as => :home_partner
  get "sign_in", :to => 'home#sign_in', :as => :home_sign_in

  get "demo_request", :to => 'demo_requests#new', :as => :new_demo_request
  post "demo_request", :to => 'demo_requests#create', :as => :create_demo_request

  get "registrations/new", :to => 'registrations#new', :as => :new_account_registration
  post "registrations", :to => 'registrations#create', :as => :create_account_registration
  get "registrations/:id", :to => 'registrations#show', :as => :account_registration
  get "registrations/:id/query/:started(.:format)", :to => 'registrations#query', :as => :query_account_registration

  ###
  # routes for tenant administration
  #

  scope 'admin' do

    devise_for :tenant_admins, :path => "" do
      # TODO: additional configuration for devise
    end

    get "impersonate/:id", :to => 'tenant_admin#impersonate', :as => :impersonate
    get ":id", :to => 'tenant_admin#show', :as => :show_account
    get "/", :to => 'tenant_admin#index', :as => :tenant_admin

  end

  ###
  # routes for tenant
  #

  # NOTE: this part of the route is "globbed" and there are some issues 
  #       in Rails when there are nested routes, so a `:tenant => current_account.subdomain` option 
  #       is required for url helpers when constructing paths
  scope "*tenant" do

    get "setup", :to => "tenant/account_setup#edit", :as => :account_setup
    put "setup", :to => "tenant/account_setup#update", :as => :update_account_setup

    devise_for :employees, :path => "" do
      # TODO: additional configuration for devise
    end

    get "welcome", :to => "tenant/dashboard#welcome", :as => :welcome

    # dashboard
    get "balance", :to => "tenant/dashboard#balance", :as => :balance

    get "staff_balance", :to => "tenant/dashboard#staff_balance", :as => :staff_balance
    post "staff_balance", :to => "tenant/dashboard#staff_balance"

    get "calendar", :to => "tenant/dashboard#calendar", :as => :calendar

    get "staff_calendar", :to => "tenant/dashboard#staff_calendar", :as => :staff_calendar
    post "staff_calendar", :to => "tenant/dashboard#staff_calendar"

    get "heatmap", :to => "tenant/dashboard#heatmap", :as => :heatmap
    post "heatmap", :to => "tenant/dashboard#heatmap"

    get "help", :to => "tenant/dashboard#help", :as => :help
    
    # profile
    get "activate", :to => "tenant/profile#activate", :as => :activate
    put "activate", :to => "tenant/profile#setactive", :as => :activate
    
    get "profile", :to => "tenant/profile#edit", :as => :profile
    put "profile", :to => "tenant/profile#update", :as => :update_profile

    # employee leave requests
    get "leave", :to => "tenant/employee_leave_requests#index", :as => :employee_leave_requests
    post "leave", :to => "tenant/employee_leave_requests#index"
    get "leave/new", :to => "tenant/employee_leave_requests#new", :as => :new_employee_leave_request
    post "leave/new", :to => "tenant/employee_leave_requests#create", :as => :create_employee_leave_request

    get "staff_leave_summary", :to => "tenant/dashboard#staff_leave_summary", :as => :staff_leave_summary
    post "staff_leave_summary", :to => "tenant/dashboard#staff_leave_summary"

    # staff leave requests
    get "staff_leave", :to => "tenant/staff_leave_requests#index", :as => :staff_leave_requests
    post "staff_leave", :to => "tenant/staff_leave_requests#index"
    get "staff_leave/new", :to => "tenant/staff_leave_requests#new", :as => :new_staff_leave_request
    post "staff_leave/new", :to => "tenant/staff_leave_requests#create", :as => :create_staff_leave_request

    # both employee and staff leave requests
    resources :leave_requests, :path => '/leave', :module => 'tenant', :except => [:index, :new, :create, :edit, :update, :destroy] do
      member do
        get 'amend'
        put 'confirm'
        put 'approve'
        put 'decline'
        put 'cancel'
        put 'reinstate'
        put 'update_constraints'
        put 'update_document'
        delete 'remove_document'
      end
    end

    get "leave_balance", :to => "tenant/leave_requests#balance", :as => :leave_balance

    # data feeds
    get "calendar_entries_feed(.:format)", :to => "tenant/data_feeds#calendar_entries", :as => :calendar_entries_feed
    get "leave_requests_feed(.:format)", :to => "tenant/data_feeds#leave_requests", :as => :leave_requests_feed

    scope "account" do

      get "edit", :to => "tenant/account#edit", :as => :edit_account
      put "edit", :to => "tenant/account#update", :as => :update_account

      get "policies", :to => "tenant/leave_types#edit", :as => :edit_leave_types
      put "policies", :to => "tenant/leave_types#update", :as => :update_leave_types

      resources :locations, :module => 'tenant'
      resources :departments, :module => 'tenant'
      
      resources :employees, :module => 'tenant' do
        collection do
          get 'filtered'
          post 'filtered'
        end

        member do
          put 'deactivate'
          put 'reactivate'
        end
      end

      get "employee_balance(.:format)", :to => "tenant/employees#balance", :as => :employee_balance

      resources :bulk_uploads, :module => 'tenant', :except => [:index] do
        member do
          get 'download'
        end
        get 'template', :on => :collection, :as => :template
        get 'records', :to => 'bulk_upload_stages#index', :as => :records
        put 'records', :to => 'bulk_upload_stages#index'
      end
      
      get "/", :to => "tenant/account#index", :as => :account

    end

    get "/", :to => "tenant/dashboard#index", :as => :dashboard

  end

  root :to => "home#index"

end

app/controllers/tenant/account_controller.rb
module Tenant
  class AccountController < AdminController
    
    def index
    end
    
    def edit
      @account = current_account
    end

    def update
      @account = current_account
      
      respond_to do |format|
        if @account.update_attributes(params[:account])
          format.html { redirect_to(edit_account_path, :notice => 'Account was successfully updated.') }
        else
          format.html { render :action => "edit" }
        end
      end
    end
    
  end
end

app/controllers/tenant/account_setup_controller.rb
require 'date'

module Tenant
  class AccountSetupController < TenantController

    skip_before_filter :check_account_active, :authenticate_employee!, :check_employee

    def initialize
      self.partials_path = 'admin'
      super
    end
    
    def edit
      @account = current_account
      
      # setup already?
      redirect_to dashboard_url and return if @account.active?
      
      registration = @account.registration
      @account_setup = AccountSetup.new().tap do |setup|
        setup.admin_first_name = registration.first_name
        setup.admin_last_name = registration.last_name
        setup.admin_user_name = registration.user_name
        setup.admin_email = registration.email
        setup.fixed_daily_hours = @account.fixed_daily_hours
        setup.leave_cycle_start_date = Date.new(Date.today.year, 1, 1)

        LeaveType.for_each_leave_type_name do |leave_type_name|
          leave_type = @account.send("leave_type_#{leave_type_name}")
          setup.send("#{leave_type_name}_leave_allowance=", leave_type.cycle_days_allowance)
        end

        setup.auth_token = @account.auth_token
        setup.auth_token_confirmation = params[:token] if @account.auth_token == params[:token]
      end
    end
    
    def update
      @account = current_account

      setup_params = params[:account_setup]
      
      # fix up the date
      setup_params[:leave_cycle_start_date] = Date.civil(
        setup_params.delete(:"leave_cycle_start_date(1i)").to_i,
        setup_params.delete(:"leave_cycle_start_date(2i)").to_i,
        setup_params.delete(:"leave_cycle_start_date(3i)").to_i
      ) unless setup_params[:leave_cycle_start_date].present?

      @account_setup = AccountSetup.new(setup_params)
      @account_setup.auth_token = @account.auth_token
      
      respond_to do |format|
        if @account_setup.save(@account) 
          sign_in(:employee, @account.employees.first)
          format.html { redirect_to(welcome_url, :notice => 'Account successfully setup.') }
        else
          format.html { render :action => "edit" }
        end
      end
    end

  end
end

app/controllers/tenant/admin_controller.rb
module Tenant
  class AdminController < TenantController

    # must be an administrator
    before_filter :ensure_admin
    
    def initialize
      self.partials_path = 'admin'
      super
    end

  end
end

app/controllers/tenant/bulk_upload_stages_controller.rb
module Tenant
  class BulkUploadStagesController < AdminController

    def index
      @bulk_upload = current_account.bulk_uploads.find(params[:bulk_upload_id])
      case params[:status]
        when 'valid'
          @records = @bulk_upload.records.where(:selected => true).page(params[:page])
        when 'errors'
          @records = @bulk_upload.records.where(:selected => false).page(params[:page])
        else
          @records = @bulk_upload.records.page(params[:page])
      end
    end

  end
end

app/controllers/tenant/bulk_uploads_controller.rb
module Tenant
  class BulkUploadsController < AdminController
    
    def new
      @bulk_upload = current_account.bulk_uploads.build()

      respond_to do |format|
        format.html # new.html.erb
      end
    end
    
    def create
      @bulk_upload = current_account.bulk_uploads.build(params[:bulk_upload])
      @bulk_upload.uploaded_by = current_employee  # will always be an admin
    
      respond_to do |format|
        if @bulk_upload.save
          format.html { redirect_to bulk_upload_url(@bulk_upload, :tenant => current_account.subdomain), 
                          :notice => 'Successfully created bulk upload. Please wait while the file is processed.' }
        else
          format.html { render :new }
        end
      end
    end
    
    def show
      @bulk_upload = current_account.bulk_uploads.find(params[:id])
      redirect_to edit_bulk_upload_url(@bulk_upload, :tenant => current_account.subdomain) if @bulk_upload.status_staged?
    end
    
    def edit
      @bulk_upload = current_account.bulk_uploads.find(params[:id])
    end
    
    def update
      @bulk_upload = current_account.bulk_uploads.find(params[:id])

      respond_to do |format|
        if @bulk_upload.set_as_accepted()
          format.html { redirect_to bulk_upload_url(@bulk_upload, :tenant => current_account.subdomain), 
                          :notice => 'Successfully queued bulk upload for import. Please wait while the data is imported.' }
        else
          format.html { render :edit }
        end
      end
    end
    
    def destroy
      @bulk_upload = current_account.bulk_uploads.find(params[:id])
      @bulk_upload.destroy
      
      redirect_to account_url, :notice => 'Successfully deleted bulk upload.'
    end
    
    def template
    end
    
    def download
      @bulk_upload = current_account.bulk_uploads.find(params[:id])
      redirect_to @bulk_upload.authenticated_url()
    end
    
  end
end

app/controllers/tenant/dashboard_controller.rb
module Tenant
  class DashboardController < TenantController
    layout 'dashboard'
    
    before_filter :handle_demo_request_trackback

    def index
      # create a holder for all the data instead of separate variables here
      @dashboard = DashboardData.new(current_account, current_employee)
    end
    
    def welcome
    end

    def balance
      @employee = params[:employee].present? ?
                    current_account.employees.find_by_identifier(params[:employee]) :
                    current_employee

      # permission check
      if @employee != current_employee && !current_employee.is_manager_of?(@employee) 
        redirect_to dashboard_url and return false
      end

      @date_as_at = safe_parse_date(params[:as_at], Date.today)
      @account = current_account
    
      # get leave types, filtered by the gender of the employee
      @leave_types = current_account.leave_types.select {|leave_type| 
        !(leave_type.gender_filter & @employee.gender_filter).empty?
      }
      
    end

    # GET & POST
    def staff_balance
      redirect_to balance_url if current_employee.is_employee?

      @leave_types = current_account.leave_types

      filter_params = params[:staff_balance_enquiry] || {}
      @staff_balance = StaffBalanceEnquiry.new(current_account, current_employee).tap do |c|
        c.date_as_at = safe_parse_date(filter_params[:date_as_at], Date.today)
        c.leave_type_id = filter_params[:leave_type_id] if filter_params[:leave_type_id]
        c.filter_by = @filter_by = filter_params[:filter_by] || 'none'
        c.location_id = filter_params[:location_id] || current_employee.location_id
        c.department_id = filter_params[:department_id] || current_employee.department_id
        c.employee_id = filter_params[:employee_id] || current_employee.id
        
        c.valid?
      end

      @employees = Kaminari.paginate_array(@staff_balance.employees).page(params[:page])
      
    end

    def calendar
    end

    # GET & POST
    def staff_calendar
      redirect_to calendar_url if current_employee.is_employee?

      filter_params = params[:staff_calendar_enquiry] || {}
      @staff_calendar = StaffCalendarEnquiry.new(current_account, current_employee).tap do |c|
        c.date_from = safe_parse_date(filter_params[:date_from], leave_cycle_start_date())
        c.date_to = safe_parse_date(filter_params[:date_to], leave_cycle_end_date())
        c.filter_by = @filter_by = filter_params[:filter_by] || 'none'
        c.location_id = filter_params[:location_id] || current_employee.location_id
        c.department_id = filter_params[:department_id] || current_employee.department_id
        c.employee_id = filter_params[:employee_id] || current_employee.id
        
        c.valid?
      end

    end
    
    # GET & POST
    def staff_leave_summary
      redirect_to dashboard_url if current_employee.is_employee?

      @leave_types = current_account.leave_types

      filter_params = params[:staff_leave_summary_enquiry] || {}
      @filter = StaffLeaveSummaryEnquiry.new(current_account, current_employee).tap do |c|
        c.date_from = safe_parse_date(filter_params[:date_from], leave_cycle_start_date())
        c.date_to = safe_parse_date(filter_params[:date_to], leave_cycle_end_date())
        c.filter_by = @filter_by = filter_params[:filter_by] || 'none'
        c.location_id = filter_params[:location_id] || current_employee.location_id
        c.department_id = filter_params[:department_id] || current_employee.department_id
        c.employee_id = filter_params[:employee_id] || current_employee.id
        
        c.valid?
      end

      @employees = Kaminari.paginate_array(@filter.employees).page(params[:page])

    end

    # GET & POST
    def heatmap
      redirect_to dashboard_url unless current_employee.is_admin? || current_employee.is_manager?
      
      filter_params = params[:heat_map_enquiry] || {}
      @heat_map = HeatMapEnquiry.new(current_account, current_employee).tap do |c| 
        c.enquiry = filter_params[:enquiry] if filter_params[:enquiry]
        
        c.date_from = safe_parse_date(filter_params[:date_from], leave_cycle_start_date())
        c.date_to = safe_parse_date(filter_params[:date_to], leave_cycle_end_date())
        c.filter_by = @filter_by = filter_params[:filter_by] || 'none'
        c.location_id = filter_params[:location_id] || current_employee.location_id
        c.department_id = filter_params[:department_id] || current_employee.department_id
        c.employee_id = filter_params[:employee_id] || current_employee.id
        
        c.valid?
      end
      
    end
    
    def help
    end

  private

    def handle_demo_request_trackback
      unless params[:r].nil?
        demo_request = DemoRequest.find(params[:r])
        demo_request.update_attributes!(:trackback => true) if demo_request
      end
    rescue
      # ignore any errors!
      true
    end

  end
end

app/controllers/tenant/data_feeds_controller.rb
module Tenant
  class DataFeedsController < TenantController

    # used in calendar control
    def calendar_entries
      from_date = Time.at(params[:start].to_i).to_date
      to_date = Time.at(params[:end].to_i).to_date

      @calendar_entries = current_account.country.calendar_entries.where(
        ' entry_date BETWEEN :from_date AND :to_date ',
        { :from_date => from_date, :to_date => to_date } 
      )
      
      respond_to do |format|
        format.json # calendar_entries.json.erb
      end
    end
    
    # used in calendar control
    def leave_requests
      from_date = Time.at(params[:start].to_i).to_date
      to_date = Time.at(params[:end].to_i).to_date

      @leave_requests = current_employee.leave_requests.active.where(
        ' (date_from BETWEEN :from_date AND :to_date ) OR ( date_to BETWEEN :from_date AND :to_date ) ',
        { :from_date => from_date, :to_date => to_date } 
      ).order('created_at DESC')
    
      respond_to do |format|
        format.json # leave_requests.json.erb
      end
    end
    
  end
end

app/views/tenant/staff_leave_requests/index.csv.erb
<%= render :partial => 'tenant/leave_requests/leave_requests', :locals => { :leave_requests => @leave_requests } %>

app/views/tenant/staff_leave_requests/index.html.erb
<% title "Staff Leave Requests" %>
<% content_title "Staff Leave Requests", "content_title_staff_leave" %>

<div id="filter" style="margin-bottom: 10px;">
  <%= form_for @filter, :as => 'leave_request_filter', :url => staff_leave_requests_path(), :remote => true do |f| %>
    <%= error_messages_for @filter %>
    <table width="100%">
      <tr>
        <td width="120px">From:</td>
        <td colspan="2" class="field"><%= f.date_picker :date_from %></td>
        <td style="text-align: right;" colspan="2">
          <div style="display: none;"><%= f.submit %></div>  
          <a id="toggle_criteria" href="javascript: toggle_criteria();" title="Hide or show additional filtering criteria">
            <%= @filter_by == 'none' ? 'More Criteria' : 'Less Criteria' %>
          </a>
        </td>
      </tr>
      <tr>
        <td>To:</td>
        <td colspan="2" class="field"><%= f.date_picker :date_to %></td>
        <td></td>
        <td></td>
      </tr>
      <tr class="extra">
        <td>Leave type:</td>
        <td class="field" colspan="2">
          <%= f.select :leave_type_id, @leave_types.collect {|e| [e.to_s, e.id]}, { :include_blank => '<All Types>' }, { :class => 'dropdown', :style => 'width: 160px;' } %>
        </td>
        <td></td>
        <td></td>
      </tr>
      <tr class="extra">
        <td></td>
        <td colspan="3" class="field" style="padding-left: 3px;">
          <%= f.check_box :requires_documentation_only %>
          <%= f.label :requires_documentation_only, 'Requires documentation?' %>
        </td>
        <td></td>
      </tr>
      <tr class="extra">
        <td style="height: 29px;"></td>
        <td width="32px"><%= f.radio_button :filter_by, 'none' %></td>
        <td colspan="2" class="field">All staff</td>
        <td></td>
      </tr>
      <tr class="extra">
        <td>Location:</td>
        <td><%= f.radio_button :filter_by, 'location' %></td>
        <td colspan="2" class="field">
          <%= f.select :location_id, current_account.locations.collect {|item| [item.title, item.to_param]}, {}, { :class => 'dropdown' } %>
        </td>
        <td></td>
      </tr>
      <tr class="extra">
        <td>Department:</td>
        <td><%= f.radio_button :filter_by, 'department' %></td>
        <td colspan="2" class="field">
          <%= f.select :department_id, current_account.departments.collect {|item| [item.title, item.to_param]}, {}, { :class => 'dropdown' } %>
        </td>
        <td></td>
      </tr>
      <tr class="extra">
        <td>Employee:</td>
        <td><%= f.radio_button :filter_by, 'employee' %></td>
        <td colspan="2" class="field">
          <%= f.select :employee_id, @filter.employees.collect {|item| [item.full_name, item.to_param]}, {}, { :class => 'dropdown' } %>
        </td>
        <td></td>
      </tr>
      <tr>
        <td colspan="5" style="height: 8px;"></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td colspan="2" style="text-align: right;">
          <%= render_buttonset(:id => 'status', :name => 'leave_request_filter[status]') do |builder| %>
            <% builder.add_button("Pending", :value => LeaveRequest::STATUS_PENDING, :checked => @filter.status?(LeaveRequest::STATUS_PENDING)) %>
            <% builder.add_button("Approved", :value => LeaveRequest::FILTER_STATUS_APPROVED, :checked => @filter.status?(LeaveRequest::FILTER_STATUS_APPROVED)) %>
            <% builder.add_button("Declined", :value => LeaveRequest::STATUS_DECLINED, :checked => @filter.status?(LeaveRequest::STATUS_DECLINED)) %>
            <% builder.add_button("Cancelled", :value => LeaveRequest::STATUS_CANCELLED, :checked => @filter.status?(LeaveRequest::STATUS_CANCELLED)) %>
          <% end %>
        </td>
      </tr>
    </table>
  <% end %>
</div>

<div style="height: 32px; margin-bottom: 10px;">
  <div id="ajax_working">Loading leave requests...</div>
  <div id="paginator" style="display: none;">
  </div>
</div>

<table id="leave_requests" class="table_grid">
  <thead>
    <tr>
      <th width="20px"></th>
      <th width="20px"></th>
      <th>Type</th>
      <th>Employee</th>
      <th>Period</th>
      <th>Requested</th>
    </tr>
  </thead>
  <tbody id="data-rows">
    <tr class="no_hover">
      <td colspan="7">
        <p>Loading leave requests...</p>
      </td>
    </tr>
  </tbody>
</table>

<p style="text-align: right;">
  <%= link_to "Download CSV", staff_leave_requests_path(
                                :format => :csv,
                                :leave_request_filter => @filter.attributes
                              ), :id => 'download_csv' %>
</p>

<script type="text/javascript">

  var extra_criteria = <%= @filter_by == 'none' ? 'false' : 'true' %>;

  $('.extra').css('display', '<%= @filter_by == 'none' ? 'none' : '' %>');

  $('#leave_request_filter_location_id').change(function(){
    $('#leave_request_filter_filter_by_location').attr('checked', 'checked');
  });

  $('#leave_request_filter_department_id').change(function(){
    $('#leave_request_filter_filter_by_department').attr('checked', 'checked');
  });

  $('#leave_request_filter_employee_id').change(function(){
    $('#leave_request_filter_filter_by_employee').attr('checked', 'checked');
  });

  function toggle_criteria() {
    extra_criteria = !extra_criteria;
    $('.extra').css('display', extra_criteria ? '' : 'none');
    $('#toggle_criteria').html(extra_criteria ? 'Less Criteria' : 'More Criteria');
  }

  $('#filter input, #filter select').change(function(){
    $('#ajax_working').css('display', '');
    $('#paginator').css('display', 'none');
    $('#leave_request_filter_new').submit();
  });

  $('#paginator a').live('ajax:before', function(e) { 
    $('#ajax_working').css('display', '');
    $('#paginator').css('display', 'none');
  });

</script>

<%= table_grid_row_click_handler %>

<script type="text/javascript" defer="defer">
  $('#leave_request_filter_new').submit();
</script>

app/views/tenant/staff_leave_requests/index.js.erb
<%= render :partial => 'tenant/leave_requests/leave_requests', :locals => { :leave_requests => @leave_requests } %>
$('#download_csv').attr('href', '<%= staff_leave_requests_path(
  :format => :csv,
  :leave_request_filter => @filter.attributes
) %>');

app/views/tenant/staff_leave_requests/new.html.erb
<% head do %>
  <%= javascript_include_tag 'chosen.jquery' %>
<% end %>

<% title "Capture Staff Leave" %>
<% content_title "Capture Staff Leave", "content_title_new_staff_leave" %>

<%= form_for(@leave_request, :html => { :multipart => true }, :url => :create_staff_leave_request) do |f| %>

  <%= error_messages_for @leave_request %>

  <div class="leave_request_container clearfix">
  
    <div class="leave_request_left">
    
      <div class="field required">
        <div><%= f.label :employee_id %></div>
        <span><%= f.select :employee_id, 
                           current_employee.staff.collect {|e| [e.to_s, e.id]}, 
                           { :include_blank => true }, 
                           :class => 'dropdown',
                           :"data-placeholder" => "Choose an employee" %></span>
        <span class="field_info"></span>
      </div>

      <div class="field required">
        <div><%= f.label :leave_type_id %></div>
        <span><%= f.select :leave_type_id, @leave_types.collect {|e| [e.to_s, e.id]}, {}, { :class => 'dropdown', :style => 'width: 158px;' } %></span>
        <span><%= f.check_box :unpaid %><%= f.label :unpaid, 'Unpaid?' %></span>
        <span class="field_info"></span>
      </div>
      
      <div class="field required">
        <div><%= f.label :date_from %></div>
        <span><%= f.date_picker :date_from %></span>
        <span><%= f.check_box :half_day_from %></span>
        <span><%= f.label :half_day_from, 'Half day?' %></span>
        <span class="field_info"></span>
      </div>

      <div class="field required">
        <div><%= f.label :date_to %></div>
        <span><%= f.date_picker :date_to %></span>
        <span><%= f.check_box :half_day_to %></span>
        <span><%= f.label :half_day_to, 'Half day?' %></span>
        <span class="field_info"></span>
      </div>

      <div class="field">
        <div><%= f.label :comment %></div>
        <span><%= f.text_area :comment, :style => 'min-width: 378px; max-width: 755px; min-height: 96px; max-height: 156px;' %></span>
        <span class="field_info"></span>
      </div>

      <div class="field">
        <div><%= f.label :document %></div>
        <span><%= f.file_field :document %></span>
        <span class="field_info"></span>
      </div>

      <% if current_employee.can_choose_own_approver? %>
        <div class="field required">
          <div><%= f.label :approver_id %></div>
          <span><%= f.select :approver_id, current_account.employees.active_approvers.collect {|e| [e.to_s, e.id]}, { :include_blank => true }, { :class => 'dropdown' } %></span>
          <span class="field_info"></span>
        </div>
      <% end %>

      <div class="actions">
        <%= f.submit 'Capture Staff Leave' %> or <%= link_to 'cancel', dashboard_path %>
      </div>

    </div>

    <div class="leave_request_right">
      <div class="panel_box box_radius box_shadow">
        <div class="panel_box_title box_radius_top">
          <div style="float: left;"><h2>Leave Balance</h2></div>
          <div id="ajax_working" style="float: right; margin-top: -4px; display: none;"></div>
        </div>
        <div id="leave_balance" class="panel_box_content">
          <%= render :partial => 'tenant/leave_requests/leave_balance', 
                     :locals => { :employee => @leave_request.employee,
                                  :leave_type => @leave_request.leave_type, 
                                  :date_from => @leave_request.date_from,
                                  :half_day_from => @leave_request.half_day_from,
                                  :date_to => @leave_request.date_to,
                                  :half_day_to => @leave_request.half_day_to,
                                  :unpaid => @leave_request.unpaid? } %>
        </div>
        <%= link_to 'Update Balance', '', :remote => true, :id => 'leave_balance_link', :style => 'display: none;' %>
      </div>
    </div>

  </div>

<% end %>

<script type="text/javascript">

  var employee = $('#leave_request_employee_id');
  var leave_type = $('#leave_request_leave_type_id');
  var date_from = $('#leave_request_date_from');
  var half_day_from = $('#leave_request_half_day_from');
  var date_to = $('#leave_request_date_to');
  var half_day_to = $('#leave_request_half_day_to');
  var unpaid = $('#leave_request_unpaid');
  
  $('.field input, .field select').change(function(){
    update_leave_balance();
  });
  
  function update_leave_balance() {
    $('#ajax_working').css('display', '');
    var path = '<%= leave_balance_url(:format => :js) %>' +
                 '?employee=' + employee.val() +
                 '&leave_type=' + leave_type.val() + 
                 '&date_from=' + date_from.val() +
                 '&half_day_from=' + (half_day_from.is(':checked') ? '1' : '0') +
                 '&date_to=' + date_to.val() +
                 '&half_day_to=' + (half_day_to.is(':checked') ? '1' : '0') +
                 '&unpaid=' + (unpaid.is(':checked') ? '1' : '0');
    $('#leave_balance_link')
      .attr('href', path)
      .click();
  }

  $("#leave_request_employee_id").chosen({no_results_text: "No employees matched"});

</script>